"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {PageHeading} from "@/components/sports";
type Status={configured:boolean;lastSuccess:string|null;error:string|null;mode:"credentials"|"session"};
export default function ConnectionPage(){
  const [status,setStatus]=useState<Status|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void fetch("/api/snp/status").then(r=>r.json()).then(s=>{if(active)setStatus(s);});return()=>{active=false;};},[]);
  async function check(){setBusy(true);setMessage("");try{const response=await fetch("/api/snp/sync?refresh=1",{method:"POST"});const sync=await response.json();setMessage(sync.ok?"Conexión verificada. Plantillas, clasificación y calendario de A y B actualizados desde SNP.":sync.warnings?.[0]||sync.error||"No se completó la consulta.");setStatus(await fetch("/api/snp/status").then(r=>r.json()));}catch{setMessage("No se pudo comprobar la conexión.");}finally{setBusy(false);}}
  const connected=status?.configured&&status.lastSuccess&&!status.error;
  return <><PageHeading eyebrow="FUENTE ORIGINAL · SNP" title="Tu conexión con SNP." text="Equipos, jugadores, clasificación, jornadas y actas desde SNP."/><section className="panel connection-panel"><span className={`badge ${connected?"blue":"muted"}`}>{connected?"SNP conectado":status?.configured?"Acceso configurado · Comprobar conexión":"Acceso pendiente de configurar"}</span><h2>Un acceso propio, también en el servidor</h2><p>La conexión usa el correo y la contraseña de SNP configurados de forma privada. El servidor inicia sesión en SNP y renueva el acceso cuando sea necesario. No necesitas dejar Chrome abierto.</p>{!status?.configured&&<><p>Añade el acceso propio de SNP en el archivo privado <code>.env.local</code>:</p><pre>SNP_EMAIL=tu_correo{"\n"}SNP_PASSWORD=tu_contraseña_de_SNP</pre><p>No uses el acceso de Google. El archivo está excluido de Git; en un despliegue, configura estos valores como secretos del servidor.</p></>}<div className="connection-actions"><button className="button" onClick={check} disabled={busy}>{busy?"Consultando SNP…":"Comprobar y actualizar"}</button><Link className="button secondary" href="/competicion">Explorar competición →</Link></div>{message&&<p className="connection-message" role="status">{message}</p>}{status?.lastSuccess&&<p>Última consulta correcta: {new Date(status.lastSuccess).toLocaleString("es-ES",{timeZone:"Europe/Madrid"})}</p>}{status?.error&&<p className="data-note">{status.error}</p>}<p className="data-note">Las pantallas consultan cada minuto mientras están abiertas. Se conservan los últimos datos si SNP no responde. Si SNP exige una verificación adicional, hay que completarla en su web. La conexión no utiliza La Cúpula.</p></section></>;
}
