"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import type { SnpPlayerProfile,SnpPlayerStats,SnpResult } from "@/domain/snp";
import { PlayerAvatar } from "./player-avatar";
import { PageHeading } from "./sports";
import { formatPoints } from "@/lib/format";
function PhaseStats({stats}:{stats:SnpPlayerStats}){
 const points=stats.jornadas.filter(j=>j.points!==null); const values=points.map(j=>j.points!); const low=Math.min(...values);const high=Math.max(...values);const dots=points.map((j,i)=>({x:24+i*552/Math.max(1,points.length-1),y:140-(j.points!-low)*110/Math.max(1,high-low),label:j.label,points:j.points}));
 return <section className="panel player-stats"><div className="panel-heading"><h2>{stats.phase}</h2></div><div className="profile-metrics">{[[stats.played,"Jugados"],[stats.won,"Ganados"],[stats.lost,"Perdidos"],[`${stats.setsWon} – ${stats.setsLost}`,"Sets G / P"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>{dots.length>0&&<div className="points-chart"><h3>Evolución de puntos por jornada</h3><svg viewBox="0 0 600 170" role="img" aria-label="Evolución de puntos SNP"><polyline points={dots.map(d=>`${d.x},${d.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="3"/>{dots.map(d=><g key={d.label}><circle cx={d.x} cy={d.y} r="5"><title>{d.label}: {formatPoints(d.points)} puntos</title></circle><text x={d.x} y="165" textAnchor="middle">{d.label}</text></g>)}</svg></div>}<div className="table-scroll"><table className="standings"><thead><tr><th>JORNADA</th><th>PARTIDOS</th><th>V</th><th>D</th><th>PUNTOS SNP</th></tr></thead><tbody>{stats.jornadas.map(j=><tr key={j.label}><td>{j.label}</td><td>{j.played}</td><td>{j.won}</td><td>{j.lost}</td><td>{formatPoints(j.points)}</td></tr>)}</tbody></table></div></section>;
}
export function ExplorerPlayer({id,teamId,backQuery=""}:{id:string;teamId?:string;backQuery?:string}){
 const [result,setResult]=useState<SnpResult<SnpPlayerProfile>|null>(null);const [error,setError]=useState("");const [group,setGroup]=useState("");const [previous,setPrevious]=useState(false);
 useEffect(()=>{const controller=new AbortController();async function update(){try{const query=new URLSearchParams();if(teamId)query.set("team",teamId);if(group)query.set("group",group);const response=await fetch(`/api/snp/players/${id}?${query}`,{signal:controller.signal});const data=await response.json();if(response.ok){setResult(data);setError("");}else setError(data.error);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Error al consultar SNP.");}}void update();const timer=setInterval(()=>{if(!document.hidden)void update();},60000);return()=>{controller.abort();clearInterval(timer);};},[id,teamId,group]);
 const player=result?.data;const stats=previous?player?.previousStats:player?.stats;
 return <><Link href={teamId?`/competicion/equipos/${teamId}${backQuery?`?${backQuery}`:""}`:"/competicion"} className="text-link back-link">← Volver {teamId?"al equipo":"a competición"}</Link><PageHeading eyebrow={`JUGADOR SNP · ${id}`} title={player?.name||"La ficha del jugador."} text="Puntos, ranking e historial deportivo"/>{(error||result?.error||player?.statsError)&&<div className="snp-warning"><span>{error||result?.error||player?.statsError}</span></div>}{player&&<><section className="panel player-profile"><PlayerAvatar name={player.name} photoUrl={player.photoUrl}/><div><h2>{formatPoints(player.points)} <small>puntos SNP</small></h2><p>Ranking nacional: {player.nationalRank||"Sin clasificación"}</p><p>Ranking zonal: {player.zoneRank||"Sin clasificación"}</p></div>{player.groups.length>0&&<label>Grupo<select value={group||player.group} onChange={e=>setGroup(e.target.value)}>{player.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}</section><div className="profile-tabs"><button className={`button ${previous?"secondary":""}`} onClick={()=>setPrevious(false)}>Temporada actual</button><button className={`button ${previous?"":"secondary"}`} onClick={()=>setPrevious(true)}>Temporada anterior</button></div>{stats?.map((s,i)=><PhaseStats key={`${s.phase}-${i}`} stats={s}/>)}{!stats?.length&&<p className="data-note">{result.source==="snapshot"?"El historial necesita una conexión SNP activa.":"SNP no devuelve historial para este grupo y temporada."}</p>}<p className="data-note">Consulta: {new Date(result.updatedAt).toLocaleString("es-ES",{timeZone:"Europe/Madrid"})} · {result.stale?"Datos guardados":"SNP"}</p></>}</>;
}

