"use client";
import {useState,useEffect} from "react";
import Link from "next/link";
import type {SnpResult,SnpTeam,SnpCompetition} from "@/domain/snp";
import {PageHeading} from "./sports";
import {PlayerAvatar} from "./player-avatar";
import {TeamLogo} from "./team-logo";
import {formatPoints,formatDate,formatTime} from "@/lib/format";
export function ExplorerTeam({id,filters}:{id:string;filters:Partial<SnpCompetition["filters"]>}){
  const [result,setResult]=useState<SnpResult<SnpTeam>|null>(null);const [error,setError]=useState("");
  const [competition,setCompetition]=useState<SnpResult<SnpCompetition>|null>(null);const filterKey=JSON.stringify(filters);
  useEffect(()=>{if(!JSON.parse(filterKey).division)return;const controller=new AbortController();async function update(){try{const response=await fetch("/api/snp/competition?"+new URLSearchParams(JSON.parse(filterKey)),{signal:controller.signal});if(response.ok){const value=await response.json();if(!controller.signal.aborted)setCompetition(value);}}catch{/* The roster remains visible if SNP cannot return a calendar. */}}void update();const timer=setInterval(()=>{if(!document.hidden)void update();},60000);return()=>{controller.abort();clearInterval(timer);};},[filterKey]);
  useEffect(()=>{let cancelled=false;async function update(){try{const response=await fetch(`/api/snp/teams/${id}`);const value=await response.json();if(cancelled)return;if(response.ok){setResult(value);setError("");}else setError(value.error);}catch{if(!cancelled)setError("No se pudo consultar el equipo.");}}void update();const timer=setInterval(()=>{if(!document.hidden)void update();},60000);return()=>{cancelled=true;clearInterval(timer);};},[id]);
  const team=result?.data;const calendar=competition?.data.calendar.filter(f=>f.homeId===id||f.awayId===id)||[];
  return <><Link href={filters.division?"/competicion?"+new URLSearchParams(JSON.parse(filterKey)):"/competicion"} className="text-link back-link">← Volver a competición</Link><PageHeading eyebrow={`EQUIPO SNP · ${id}`} title={team?.name||"La plantilla del equipo."} text={team?`${team.players.length} jugadores · Puntos y ranking SNP`:"Consultando ficha…"} logoName={team?.name}/>{(error||result?.error)&&<p className="snp-warning" role="status">{error||result?.error} </p>}{team&&<><section className="panel"><div className="panel-heading"><h2>Plantilla</h2><span className="badge blue">{result.stale?"Consulta guardada":"SNP"}</span></div><div className="roster-list">{[...team.players].sort((a,b)=>b.points-a.points).map((player,index)=><Link className="roster-row" key={player.id} href={`/competicion/jugadores/${player.id}?equipo=${id}&${new URLSearchParams(JSON.parse(filterKey))}`}><span className="roster-rank">{String(index+1).padStart(2,"0")}</span><PlayerAvatar name={player.name} photoUrl={player.photoUrl}/><div className="roster-name"><strong>{player.name}</strong><span>Ver ficha del jugador →</span></div><div className="roster-points"><strong>{formatPoints(player.points)}</strong><span>PTS SNP</span></div></Link>)}</div></section>{filters.division&&<section className="panel explorer-rounds"><div className="panel-heading"><h2>Calendario y resultados del equipo</h2></div>{competition?.error&&<p className="snp-warning">{competition.error}</p>}{calendar.map(f=><Link key={f.id} href={`/competicion/actas/${f.id}`} className="explorer-match"><span className="explorer-date">J{f.round}<small>{formatDate(f.date||"")} · {formatTime(f.date||"")}</small></span><span><TeamLogo name={f.homeName}/><strong>{f.homeName}</strong></span><b>{f.score?f.score.join(" – "):"VS"}</b><span><TeamLogo name={f.awayName}/><strong>{f.awayName}</strong></span><span className="match-arrow">→</span></Link>)}{competition&&!calendar.length&&<p className="data-note">SNP no publica encuentros de este equipo en la división seleccionada.</p>}</section>}<p className="data-note">Consulta: {new Date(result.updatedAt).toLocaleString("es-ES",{timeZone:"Europe/Madrid"})} · {result.stale?"Datos guardados":"Fuente original SNP"}</p></>}</>;
}

